version: '3.8'
services:
  postgres:
    image: postgres:13
    restart: always
    volumes:
      - postgresql-data:/var/lib/postgresql/data
      - ./db:/code
    environment:
      - POSTGRES_USER=postgresql
      - POSTGRES_PASSWORD=postgresql
      - POSTGRES_DB=postgresql
    env_file:
      - ./db/.env
    ports:
      - 5432:5432
    
  backend:
    build:
      context: ./
      dockerfile: Dockerfile.dev
    restart: always
    environment:
      - ENV_RUNTIME=dev
    env_file:
      - ./.env
    ports:
      - "8080:8080"
    depends_on: 
      - postgres


volumes:
  postgresql-data:
    driver: local
